export const filterItems: string[] = ['tag', 'climber'];

export const ropeClimbingGrades: string[] = [
  '5.0',
  '5.1',
  '5.2',
  '5.3',
  '5.4',
  '5.5',
  '5.6',
  '5.7',
  '5.8',
  '5.9',
  '5.10a',
  '5.10b',
  '5.10c',
  '5.10d',
  '5.11a',
  '5.11b',
  '5.11c',
  '5.11d',
  '5.12a',
  '5.12b',
  '5.12c',
  '5.12d',
  '5.13a',
  '5.13b',
  '5.13c',
  '5.13d',
  '5.14a',
  '5.14b',
  '5.14c',
  '5.14d',
  '5.15a',
  '5.15b',
  '5.15c',
  '5.15d',
];

export const boulderingClimbingGrades = [
  'V0',
  'V1',
  'V2',
  'V3',
  'V4',
  'V5',
  'V6',
  'V7',
  'V8',
  'V9',
  'V10',
  'V11',
  'V12',
  'V13',
  'V14',
  'V15',
  'V16',
];

export const friendsOnMapExample = [
  {
    id: 1,
    firstName: 'Liam',
    lastName: 'Brown',
    email: 'liam.brown@example.com',
    userName: 'liamthelion',
  },
  {
    id: 5,
    firstName: 'Elijah',
    lastName: 'Smith',
    email: 'elijah.smith@example.com',
    userName: 'elirunner',
  },
  {
    id: 3,
    firstName: 'Noah',
    lastName: 'Williams',
    email: 'noah.wills@example.com',
    userName: 'noahwave',
  },
  {
    id: 2,
    firstName: 'Emma',
    lastName: 'Johnson',
    email: 'emma.johnson@example.com',
    userName: 'emmajay',
  },
  {
    id: 6,
    firstName: 'Ava',
    lastName: 'Miller',
    email: 'ava.miller@example.com',
    userName: 'avamuse',
  },
];

export const climbType: Array<string> = ['Rock', 'Boulder', 'All'];

export const climbTypeForFilter: Array<string> = ['Rock', 'Boulder', 'None'];
export const usStateAbbreviations: string[] = [
  'AL',
  'AK',
  'AZ',
  'AR',
  'CA',
  'CO',
  'CT',
  'DE',
  'FL',
  'GA',
  'HI',
  'ID',
  'IL',
  'IN',
  'IA',
  'KS',
  'KY',
  'LA',
  'ME',
  'MD',
  'MA',
  'MI',
  'MN',
  'MS',
  'MO',
  'MT',
  'NE',
  'NV',
  'NH',
  'NJ',
  'NM',
  'NY',
  'NC',
  'ND',
  'OH',
  'OK',
  'OR',
  'PA',
  'RI',
  'SC',
  'SD',
  'TN',
  'TX',
  'UT',
  'VT',
  'VA',
  'WA',
  'WV',
  'WI',
  'WY',
];

export const usStateDictionary: { [key: string]: string } = {
  AL: 'Alabama',
  AK: 'Alaska',
  AZ: 'Arizona',
  AR: 'Arkansas',
  CA: 'California',
  CO: 'Colorado',
  CT: 'Connecticut',
  DE: 'Delaware',
  FL: 'Florida',
  GA: 'Georgia',
  HI: 'Hawaii',
  ID: 'Idaho',
  IL: 'Illinois',
  IN: 'Indiana',
  IA: 'Iowa',
  KS: 'Kansas',
  KY: 'Kentucky',
  LA: 'Louisiana',
  ME: 'Maine',
  MD: 'Maryland',
  MA: 'Massachusetts',
  MI: 'Michigan',
  MN: 'Minnesota',
  MS: 'Mississippi',
  MO: 'Missouri',
  MT: 'Montana',
  NE: 'Nebraska',
  NV: 'Nevada',
  NH: 'New Hampshire',
  NJ: 'New Jersey',
  NM: 'New Mexico',
  NY: 'New York',
  NC: 'North Carolina',
  ND: 'North Dakota',
  OH: 'Ohio',
  OK: 'Oklahoma',
  OR: 'Oregon',
  PA: 'Pennsylvania',
  RI: 'Rhode Island',
  SC: 'South Carolina',
  SD: 'South Dakota',
  TN: 'Tennessee',
  TX: 'Texas',
  UT: 'Utah',
  VT: 'Vermont',
  VA: 'Virginia',
  WA: 'Washington',
  WV: 'West Virginia',
  WI: 'Wisconsin',
  WY: 'Wyoming',
};

export const filterTypes: string[] = [
  'Order By Grade ASC',
  'Order By Grade DESC',
];

export const conversation = [
  { name: 'Micah', message: 'Hey everyone, how’s it going?' },
  {
    name: 'Theresa',
    message: 'Pretty good! Just finished a big project at work. How about you?',
  },
  {
    name: 'Ben',
    message:
      'I’m doing well, just enjoying the weekend. What project were you working on, Theresa?',
  },
  {
    name: 'Theresa',
    message:
      'It was a website redesign for a client. Took a lot longer than expected, but it’s finally done!',
  },
  {
    name: 'Micah',
    message:
      'Congrats on finishing it, Theresa! That must feel like a big relief.',
  },
  {
    name: 'Theresa',
    message: 'Definitely! Thanks, Micah. Any plans for the weekend?',
  },
  {
    name: 'Ben',
    message:
      'I’m thinking of going hiking tomorrow if the weather’s good. You guys interested?',
  },
  {
    name: 'Micah',
    message: 'I’m down! Been wanting to get out and stretch my legs.',
  },
  {
    name: 'Theresa',
    message: 'Sounds like fun! Count me in if I’m not too tired.',
  },
  {
    name: 'Ben',
    message: 'Awesome! Let’s meet up in the morning then. Can’t wait!',
  },
];
