export const exampleMapObjects = [
  {
    id: 1,
    name: 'Leavenworth Fall 2024',
    description: 'Micah and Friends Leavenworth climbing map for fall 2024',
    totalClimbs: 782,
    peopleOnMap: [
      {
        id: 1,
        firstName: 'Liam',
        lastName: 'Brown',
        email: 'liam.brown@example.com',
        userName: 'liamthelion',
      },
      {
        id: 7,
        firstName: 'James',
        lastName: 'Davis',
        email: 'james.davis@example.com',
        userName: 'jimmysport',
      },
      {
        id: 3,
        firstName: 'Noah',
        lastName: 'Williams',
        email: 'noah.wills@example.com',
        userName: 'noahwave',
      },
      {
        id: 6,
        firstName: 'Ava',
        lastName: 'Miller',
        email: 'ava.miller@example.com',
        userName: 'avamuse',
      },
      {
        id: 2,
        firstName: 'Emma',
        lastName: 'Johnson',
        email: 'emma.johnson@example.com',
        userName: 'emmajay',
      },
    ],
  },
  {
    id: 2,
    name: 'Yosemite Spring 2024',
    description: 'Spring adventure at Yosemite with the big wall crew',
    totalClimbs: 350,
    peopleOnMap: [
      {
        id: 9,
        firstName: 'Ethan',
        lastName: 'Garcia',
        email: 'ethan.garcia@example.com',
        userName: 'ethangamer',
      },
      {
        id: 4,
        firstName: 'Olivia',
        lastName: 'Jones',
        email: 'olivia.jones@example.com',
        userName: 'olivebranch',
      },
      {
        id: 10,
        firstName: 'Sophia',
        lastName: 'Rodriguez',
        email: 'sophia.rodriguez@example.com',
        userName: 'sophistar',
      },
      {
        id: 8,
        firstName: 'Isabella',
        lastName: 'Martinez',
        email: 'isabella.martinez@example.com',
        userName: 'bellaart',
      },
      {
        id: 7,
        firstName: 'James',
        lastName: 'Davis',
        email: 'james.davis@example.com',
        userName: 'jimmysport',
      },
    ],
  },
  {
    id: 3,
    name: 'Red Rocks Winter 2024',
    description: 'Winter climbing escape in Red Rocks for the desert lovers',
    totalClimbs: 420,
    peopleOnMap: [
      {
        id: 4,
        firstName: 'Olivia',
        lastName: 'Jones',
        email: 'olivia.jones@example.com',
        userName: 'olivebranch',
      },
      {
        id: 6,
        firstName: 'Ava',
        lastName: 'Miller',
        email: 'ava.miller@example.com',
        userName: 'avamuse',
      },
      {
        id: 2,
        firstName: 'Emma',
        lastName: 'Johnson',
        email: 'emma.johnson@example.com',
        userName: 'emmajay',
      },
      {
        id: 8,
        firstName: 'Isabella',
        lastName: 'Martinez',
        email: 'isabella.martinez@example.com',
        userName: 'bellaart',
      },
      {
        id: 1,
        firstName: 'Liam',
        lastName: 'Brown',
        email: 'liam.brown@example.com',
        userName: 'liamthelion',
      },
    ],
  },
  {
    id: 4,
    name: 'Joshua Tree New Year 2025',
    description:
      'Celebrating the New Year at Joshua Tree with campfire sessions',
    totalClimbs: 530,
    peopleOnMap: [
      {
        id: 7,
        firstName: 'James',
        lastName: 'Davis',
        email: 'james.davis@example.com',
        userName: 'jimmysport',
      },
      {
        id: 6,
        firstName: 'Ava',
        lastName: 'Miller',
        email: 'ava.miller@example.com',
        userName: 'avamuse',
      },
      {
        id: 10,
        firstName: 'Sophia',
        lastName: 'Rodriguez',
        email: 'sophia.rodriguez@example.com',
        userName: 'sophistar',
      },
      {
        id: 9,
        firstName: 'Ethan',
        lastName: 'Garcia',
        email: 'ethan.garcia@example.com',
        userName: 'ethangamer',
      },
      {
        id: 3,
        firstName: 'Noah',
        lastName: 'Williams',
        email: 'noah.wills@example.com',
        userName: 'noahwave',
      },
    ],
  },
  {
    id: 5,
    name: 'Squamish Summer 2025',
    description:
      'Summer trad climbing and bouldering in Squamish with the Canadian crew',
    totalClimbs: 610,
    peopleOnMap: [
      {
        id: 1,
        firstName: 'Liam',
        lastName: 'Brown',
        email: 'liam.brown@example.com',
        userName: 'liamthelion',
      },
      {
        id: 5,
        firstName: 'Elijah',
        lastName: 'Smith',
        email: 'elijah.smith@example.com',
        userName: 'elirunner',
      },
      {
        id: 3,
        firstName: 'Noah',
        lastName: 'Williams',
        email: 'noah.wills@example.com',
        userName: 'noahwave',
      },
      {
        id: 2,
        firstName: 'Emma',
        lastName: 'Johnson',
        email: 'emma.johnson@example.com',
        userName: 'emmajay',
      },
      {
        id: 6,
        firstName: 'Ava',
        lastName: 'Miller',
        email: 'ava.miller@example.com',
        userName: 'avamuse',
      },
    ],
  },
  {
    id: 6,
    name: 'Rocklands Autumn 2025',
    description:
      'Exploring the boulders of Rocklands, South Africa in the fall',
    totalClimbs: 895,
    peopleOnMap: [
      {
        id: 8,
        firstName: 'Isabella',
        lastName: 'Martinez',
        email: 'isabella.martinez@example.com',
        userName: 'bellaart',
      },
      {
        id: 2,
        firstName: 'Emma',
        lastName: 'Johnson',
        email: 'emma.johnson@example.com',
        userName: 'emmajay',
      },
      {
        id: 4,
        firstName: 'Olivia',
        lastName: 'Jones',
        email: 'olivia.jones@example.com',
        userName: 'olivebranch',
      },
      {
        id: 9,
        firstName: 'Ethan',
        lastName: 'Garcia',
        email: 'ethan.garcia@example.com',
        userName: 'ethangamer',
      },
      {
        id: 1,
        firstName: 'Liam',
        lastName: 'Brown',
        email: 'liam.brown@example.com',
        userName: 'liamthelion',
      },
    ],
  },
];

export const friendExample = [
  {
    firstName: 'Liam',
    lastName: 'Brown',
    id: 1,
    email: 'liam.brown@example.com',
    userName: 'liamthelion',
  },
  {
    firstName: 'Emma',
    lastName: 'Johnson',
    id: 2,
    email: 'emma.johnson@example.com',
    userName: 'emmajay',
  },
  {
    firstName: 'Noah',
    lastName: 'Williams',
    id: 3,
    email: 'noah.wills@example.com',
    userName: 'noahwave',
  },
  {
    firstName: 'Olivia',
    lastName: 'Jones',
    id: 4,
    email: 'olivia.jones@example.com',
    userName: 'olivebranch',
  },
  {
    firstName: 'Elijah',
    lastName: 'Smith',
    id: 5,
    email: 'elijah.smith@example.com',
    userName: 'elirunner',
  },
  {
    firstName: 'Ava',
    lastName: 'Miller',
    id: 6,
    email: 'ava.miller@example.com',
    userName: 'avamuse',
  },
  {
    firstName: 'James',
    lastName: 'Davis',
    id: 7,
    email: 'james.davis@example.com',
    userName: 'jimmysport',
  },
  {
    firstName: 'Isabella',
    lastName: 'Martinez',
    id: 8,
    email: 'isabella.martinez@example.com',
    userName: 'bellaart',
  },
  {
    firstName: 'Ethan',
    lastName: 'Garcia',
    id: 9,
    email: 'ethan.garcia@example.com',
    userName: 'ethangamer',
  },
  {
    firstName: 'Sophia',
    lastName: 'Rodriguez',
    id: 10,
    email: 'sophia.rodriguez@example.com',
    userName: 'sophistar',
  },
];
