using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;

namespace ClimbWithFriendsAPI.Data
{
    public class User
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int UserId { get; set; } 

        public string Auth0ID { get; set; } // ID generated by auth0

        public string Username { get; set; } = string.Empty;

        public string Name {  get; set; }

        [EmailAddress] // Ensures the format of this field is a valid email
        public string Email { get; set; } = string.Empty;

        public DateTime? CreatedAt { get; set; } // When the user was created

        
    }
}
