[phases.setup]
nixPkgs = ["dotnet-sdk_8_0"]

[phases.install]
cmds = ["dotnet restore --no-cache"]

[phases.build]
cmds = ["dotnet publish -c Release -o /app/publish --no-restore"]

[start]
cmd = "dotnet ClimbWithFriendsAPI.dll" 