[build]
builder = "dockerfile"

[deploy]
startCommand = "dotnet ClimbWithFriendsAPI.dll"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
numReplicas = 1

[env]
ASPNETCORE_ENVIRONMENT = "Production" 